apiVersion: apps/v1
kind: Deployment
metadata:
  name: translation-api
  labels:
    app: translation-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: translation-api
  template:
    metadata:
      labels:
        app: translation-api
    spec:
      containers:
      - name: translation-api
        image: qscez2001/translate-imae
        ports:
        - containerPort: 9527
---
apiVersion: v1
kind: Service
metadata:
  name: translation-service
spec:
  selector:
    app: translation-api
  ports:
    - protocol: TCP
      port: 9527
      targetPort: 9527
  type: LoadBalancer
